name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  build:
    needs: checks
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: |
          mkdir dist
          go build -ldflags="-H=windowsgui" -o ./dist/mfeederd.exe ./daemon/
          go build -o ./dist/mfeeder.exe ./cli/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mfeeder-windows-binaries-${{ github.sha }}
          path: |
            ./dist/mfeederd.exe
            ./dist/mfeeder.exe
          retention-days: 30
